/**
 * Sifa SDK -- public client library for the Sifa AppView on AT Protocol.
 *
 * Pre-1.0: the public API is unstable and may change in any minor release.
 *
 * @see https://github.com/singi-labs/sifa-sdk
 */

declare const __SIFA_SDK_VERSION__: string;

export const SIFA_SDK_VERSION: string = __SIFA_SDK_VERSION__;

export type {
  ActiveApp,
  Endorsement,
  EndorsementData,
  ExternalAccount,
  ExternalAccountKeytraceClaim,
  FeedItem,
  LanguageProficiency,
  LocationValue,
  PdsProviderInfo,
  Profile,
  ProfileCertification,
  ProfileCourse,
  ProfileEducation,
  ProfileHonor,
  ProfileIndustry,
  ProfileLanguage,
  ProfileLocation,
  ProfileOverrideSource,
  ProfilePosition,
  ProfileProject,
  ProfilePublication,
  ProfileSkill,
  ProfileVolunteering,
  PublicationContributor,
  SkillRef,
  SkillSuggestion,
  TrustStat,
  VerifiedAccount,
} from './types/index.js';

export {
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  CONTINENTS,
  COUNTRIES,
  EMPLOYMENT_TYPE_GROUPS,
  EMPLOYMENT_TYPE_LABELS,
  INDUSTRY_OPTIONS,
  OPEN_TO_OPTIONS,
  findIndustry,
  getEmploymentTypeLabel,
  getIndustryLabelKey,
  getOpenToLabelKey,
  getWorkplaceTypeLabel,
  PLATFORM_LABELS,
  PLATFORM_OPTIONS,
  SKILL_CATEGORIES,
  WORKPLACE_TYPE_LABELS,
  WORKPLACE_TYPE_OPTIONS,
  dedupeSkills,
  getContinent,
  getFaviconUrl,
  getPlatformLabel,
  groupSkillsByCategory,
  isKnownPlatform,
  type ContinentCode,
  type EmploymentTypeGroup,
  type EmploymentTypeOption,
  type IndustryOption,
  type MergedProfileSkill,
  type OpenToOption,
  type PlatformId,
  type SkillCategory,
  type WorkplaceTypeOption,
} from './taxonomy/index.js';

export {
  certDateExtractor,
  contrastRatio,
  countryCodeToFlag,
  dateRangeExtractor,
  detectPdsProvider,
  formatDistanceToNow,
  formatLocation,
  formatRelativeTime,
  getDisplayLabel,
  getHandleStem,
  getPdsDisplayName,
  isValidRgbColor,
  lexiconDateExtractor,
  limitCombiningMarks,
  meetsContrastAA,
  parseLocationString,
  pdsProviderFromApi,
  relativeLuminance,
  rgbToString,
  sanitizeDisplayText,
  sanitizeHandleInput,
  singleDateExtractor,
  sortByDateDesc,
  truncateGraphemes,
  type PdsProvider,
  type RgbColor,
} from './format/index.js';

export {
  COMPLETENESS_MAX_SCORE,
  completenessPercent,
  completenessScore,
  DIMENSIONS_MAX_SCORE,
  MIN_SKILLS,
  countFilledDimensions,
  dimensionsFromInputs,
  getFilledDimensionsMap,
  profileToDimensionInputs,
  type DimensionKey,
  type DimensionMap,
  type ProfileCompletion,
  type ProfileDimensionInputs,
} from './logic/index.js';

export {
  EndorsementConfirmationRecordSchema,
  EndorsementRecordSchema,
  GraphFollowRecordSchema,
  ProfileCertificationRecordSchema,
  ProfileCourseRecordSchema,
  ProfileEducationRecordSchema,
  ProfileExternalAccountRecordSchema,
  ProfileHonorRecordSchema,
  ProfileLanguageRecordSchema,
  ProfilePositionRecordSchema,
  ProfileProjectRecordSchema,
  ProfilePublicationRecordSchema,
  ProfileSelfRecordSchema,
  ProfileSkillRecordSchema,
  ProfileVolunteeringRecordSchema,
  PublicationAuthorSchema,
  atUriSchema,
  cidSchema,
  datetimeSchema,
  didSchema,
  languageTagSchema,
  maxGraphemes,
  selfLabelsSchema,
  strongRefSchema,
  uriSchema,
  type EndorsementConfirmationRecord,
  type EndorsementRecord,
  type GraphFollowRecord,
  type ProfileCertificationRecord,
  type ProfileCourseRecord,
  type ProfileEducationRecord,
  type ProfileExternalAccountRecord,
  type ProfileHonorRecord,
  type ProfileLanguageRecord,
  type ProfilePositionRecord,
  type ProfileProjectRecord,
  type ProfilePublicationRecord,
  type ProfileSelfRecord,
  type ProfileSkillRecord,
  type ProfileVolunteeringRecord,
  type PublicationAuthor,
} from './schemas/index.js';
