/**
 * Sifa SDK -- public client library for the Sifa AppView on AT Protocol.
 *
 * Pre-1.0: the public API is unstable and may change in any minor release.
 *
 * @see https://github.com/singi-labs/sifa-sdk
 */

declare const __SIFA_SDK_VERSION__: string;

export const SIFA_SDK_VERSION: string = __SIFA_SDK_VERSION__;

export type {
  ActiveApp,
  Endorsement,
  EndorsementData,
  ExternalAccount,
  ExternalAccountKeytraceClaim,
  FeedItem,
  LanguageProficiency,
  LocationValue,
  PdsProviderInfo,
  Profile,
  ProfileCertification,
  ProfileCourse,
  ProfileEducation,
  ProfileHonor,
  ProfileIndustry,
  ProfileLanguage,
  ProfileLocation,
  ProfileOverrideSource,
  ProfilePosition,
  ProfileProject,
  ProfilePublication,
  ProfileSkill,
  ProfileVolunteering,
  PublicationContributor,
  SkillRef,
  SkillSuggestion,
  TrustStat,
  VerifiedAccount,
} from './types/index.js';

export {
  ACTIVITY_TIERS,
  APP_CATEGORIES,
  APP_CATEGORY_IDS,
  APP_CATEGORY_MAP,
  CATEGORY_LABELS,
  CATEGORY_ORDER,
  CONTINENTS,
  COUNTRIES,
  EMPLOYMENT_TYPE_GROUPS,
  EMPLOYMENT_TYPE_LABELS,
  INDUSTRY_OPTIONS,
  OPEN_TO_OPTIONS,
  categoryForApp,
  findIndustry,
  getActivityTaxonomyVersion,
  getActivityTier,
  getAppCategoryIcon,
  getEmploymentTypeLabel,
  getIndustryLabelKey,
  getLexiconEntry,
  getOpenToLabelKey,
  getTierMeta,
  getWorkplaceTypeLabel,
  isAppCategory,
  isKnownAppId,
  PLATFORM_LABELS,
  PLATFORM_OPTIONS,
  SKILL_CATEGORIES,
  WORKPLACE_TYPE_LABELS,
  WORKPLACE_TYPE_OPTIONS,
  dedupeSkills,
  getContinent,
  getFaviconUrl,
  getPlatformLabel,
  groupSkillsByCategory,
  isKnownPlatform,
  type ActivityTaxonomy,
  type ActivityTier,
  type AppCategoryId,
  type ContinentCode,
  type EmploymentTypeGroup,
  type EmploymentTypeOption,
  type IndustryOption,
  type KnownAppId,
  type LexiconEntry,
  type MergedProfileSkill,
  type OpenToOption,
  type PlatformId,
  type SkillCategory,
  type TierMeta,
  type WorkplaceTypeOption,
} from './taxonomy/index.js';

export {
  certDateExtractor,
  contrastRatio,
  countryCodeToFlag,
  dateRangeExtractor,
  detectPdsProvider,
  formatDistanceToNow,
  formatLocation,
  formatRelativeTime,
  getDisplayLabel,
  getHandleStem,
  getPdsDisplayName,
  isValidRgbColor,
  lexiconDateExtractor,
  limitCombiningMarks,
  meetsContrastAA,
  parseLocationString,
  pdsProviderFromApi,
  relativeLuminance,
  rgbToString,
  sanitizeDisplayText,
  sanitizeHandleInput,
  singleDateExtractor,
  sortByDateDesc,
  truncateGraphemes,
  type PdsProvider,
  type RgbColor,
} from './format/index.js';

export {
  ACTIVITY_VISIBILITY_RULES,
  APP_URL_PATTERNS,
  COLLECTION_TO_APP,
  getAppIdForCollection,
  isVisibleActivityItem,
  resolveCardUrl,
  type ActivityItemForUrl,
  type AppUrlPatterns,
} from './cards/index.js';

export {
  COMPLETENESS_MAX_SCORE,
  completenessPercent,
  completenessScore,
  DIMENSIONS_MAX_SCORE,
  MIN_SKILLS,
  countFilledDimensions,
  dimensionsFromInputs,
  getFilledDimensionsMap,
  pickPrimaryPosition,
  profileToDimensionInputs,
  type DimensionKey,
  type DimensionMap,
  type PrimaryPositionCandidate,
  type ProfileCompletion,
  type ProfileDimensionInputs,
} from './logic/index.js';

export {
  AtmosphereFeedItemSchema,
  EndorsementConfirmationRecordSchema,
  EndorsementRecordSchema,
  FEATURE_FLAGS,
  FeatureAllowlistEntrySchema,
  FeedActorSchema,
  FollowFeedItemSchema,
  FollowFeedPageSchema,
  FollowProfilePageSchema,
  FollowProfileSchema,
  GraphFollowRecordSchema,
  ProfileCertificationRecordSchema,
  ProfileCourseRecordSchema,
  ProfileEducationRecordSchema,
  ProfileExternalAccountRecordSchema,
  ProfileHonorRecordSchema,
  ProfileLanguageRecordSchema,
  ProfilePositionRecordSchema,
  ProfileProjectRecordSchema,
  ProfilePublicationRecordSchema,
  ProfileSelfRecordSchema,
  ProfileSkillRecordSchema,
  ProfileVolunteeringRecordSchema,
  PublicationAuthorSchema,
  SifaFeedItemSchema,
  atUriSchema,
  cidSchema,
  datetimeSchema,
  decodeFeedCursor,
  didSchema,
  encodeFeedCursor,
  languageTagSchema,
  makeGraphFollowRecordSchema,
  maxGraphemes,
  selfLabelsSchema,
  strongRefSchema,
  uriSchema,
  type AtmosphereFeedItem,
  type EndorsementConfirmationRecord,
  type EndorsementRecord,
  type FeatureAllowlistEntry,
  type FeatureFlag,
  type FeedActor,
  type FeedCursor,
  type FollowFeedItem,
  type FollowFeedPage,
  type FollowProfileItem,
  type FollowProfilePage,
  type GraphFollowRecord,
  type SifaFeedItem,
  type ProfileCertificationRecord,
  type ProfileCourseRecord,
  type ProfileEducationRecord,
  type ProfileExternalAccountRecord,
  type ProfileHonorRecord,
  type ProfileLanguageRecord,
  type ProfilePositionRecord,
  type ProfileProjectRecord,
  type ProfilePublicationRecord,
  type ProfileSelfRecord,
  type ProfileSkillRecord,
  type ProfileVolunteeringRecord,
  type PublicationAuthor,
} from './schemas/index.js';
